config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :groups
  resources :groups do
    get 'create_event', to: 'groups#create_event'
  end
  resources :users
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :members, only: [:new, :create, :show, :destroy]  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :members
  validates :name, presence: true, 
            length: {minimum: 3, maximum: 20} 
end  

app/models/member.rb
class Member < ApplicationRecord
  before_save { self.email = email.downcase }
  belongs_to :group
  validates :name, presence: true, 
                       length: {minimum: 3, maximum: 20}
  validates :email, presence: true, 
                    length: {maximum: 105},
                    format: {with: /\A\S+@.+\.\S+\z/}
end  

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :username, presence: true, 
                       uniqueness: { case_sensitive: false },
                       length: {minimum: 3, maximum: 20}
  validates :email, presence: true, 
                    uniqueness: { case_sensitive: false },
                    length: {maximum: 105},
                    format: {with: /\A\S+@.+\.\S+\z/}
  has_secure_password                                   
end  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
    
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]            
  end 
  
  def logged_in?
    !!current_user
  end     

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in."
      redirect_to login_path 
    end      
  end  
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :require_user, only: [:show, :edit, :update, :destroy, :create_event, :create_event]
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :set_current_group_id, only: [:create_event]
  def new
    @group = Group.new
  end

  def index
    @groups = Group.all
  end    

    def show
    @members = @group.members
  end    

  def edit
  end  

  def create
    @group = Group.new(group_params)
    @group.user = current_user
    if  @group.save
      flash[:notice] = "Group was created successfully"
      redirect_to @group         
    else
      render 'new'
    end    

  end  

  def destroy
    @group.destroy
    redirect_to groups_path
  end  


  private 
  def group_params
    params.require(:group).permit(:name)
  end    

  def set_group
    @group = Group.find_by_id(params[:id]) 
    session[:current_group_id]=@group.id    
  end 

  def set_current_group_id
    @current_group_id = session[:current_group_id]
  end 
  
end  

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_current_group_id, only: [:create, :destroy]
  before_action :set_member, only: [:destroy]

  def new
    @member = Member.new
  end 

  def show 
  end  
  
  def index
   @members = Member.all
  end  

  def create
    @member = Member.new(member_params)
    @member.group_id = session[:current_group_id]    
    if @member.save
      redirect_to group_path(Group.find_by_id(session[:current_group_id]))
    else
      render 'new'
    end    
  end  
  
  def destroy
    @member.destroy
    redirect_to group_path(Group.find_by_id(session[:current_group_id]))
  end  


  private 
  def member_params
    params.require(:member).permit(:name, :email)
  end

  def set_member
    @member = Member.find(params[:id])   
  end 

  def set_current_group_id
    current_group_id = session[:current_group_id]
  end   

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end  
end  

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new    
    end
        
    def create    
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:notice] = "Logged successfully."
            redirect_to groups_url
        else  
            flash.now[:alert] = "Your email or password was incorrect."
            render 'new'
        end      
    end    
    
    def destroy
        session[:user_id] = nil 
        flash[:notice] = "You were logged out."
        redirect_to root_path
    end    


end     

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]

    def show        
      @groups = @user.groups   
    end
   
    def new
      @user = User.new
    end
    
    def edit        
    end
    
     def update      
         if @user.update(user_params)
          flash[:notice] = "Your account was updated successfully."
             redirect_to groups_url  
         else
             render 'edit'
         end    
     end    
    
     def create
        @user = User.new(user_params)
        if @user.save
          session[:user_id] = @user.id
          flash[:notice] = "Your account was creates successfully."
          redirect_to groups_path
         else
             render 'new'
         end        
     end
    
   def destroy
         @user.destroy
         session[:user_id] = nil if @user == current_user
         flash[:notice] = "Account and groups successfull deleted."
         redirect_to root_path        
     end    
    
    
    
    
     private   
    
     def user_params
          params.require(:user).permit(:username, :email, :password)
     end       
    
     def set_user
         @user = User.find(params[:id])
     end    

     def require_same_user
        if current_user != @user
          flash[:alert] = "You can only edit or delete your account"
          redirect_to groups_url
        end    
     end    
end  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.erb
<div class="container mt-5" id="new-group-container">
  <%= form_with(model: @group, local: true) do |f|%>
    <div class="input-group mb-3">
        <%= f.label :name, class: "input-group-text" %>
        <div class="col-10"> 
          <%= f.text_field :name, class: "form-control shadow-lg rounded", placeholder: "Enter group name" %>
        </div>   
    </div>  
    <div class="mt-4">     
      <%= link_to "Cancel", groups_path(@groups),data: { confirm: "Your group will be not saved!"}, class: " btn btn-outline-danger btn-lg "%>
      <%= f.submit class:"btn btn-outline-secondary btn-lg right "%>
    </div>
  <%end%>     
</div>

app/views/groups/create_event.html.erb
<h1 class="display-4 mt-5">Create event</h1>

<%= @emails %>
<%= @current_group_id %>
<%= session[:current_group_id] %>

app/views/groups/edit.html.erb
<h1 class="display-4 mt-5">Edit group: <%= @group.name %></h1>
<%= render 'form' %>

app/views/groups/index.html.erb
<h1 class="display-4 mt-3">Your groups</h1>
<div class="text-center mt-3">
  <%= link_to "Create new group", new_group_path, class: "btn btn-outline-success btn-lg justify-content-md-center"  %>
</div>
<div class="container mt-3" id="groups-index-container">
  <table class="table ">
    <thead>
      <tr>
        <th scope="col">Group name</th>
        <th scope="col">Number of members</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
    <% current_user.groups.each do |group| %>
      <tr>        
        <td><%= group.name %></td>
        <td><%= pluralize(group.members.count, "member") %></td>
        <td>
            <%= link_to "View", group_path(group),  class: "btn btn-outline-info btn-sm"  %>
            <%= link_to "Delete", group_path(group), method: :delete, data: { confirm: "Are you sure?"} , class: "btn btn-outline-danger btn-sm"%>
        </td>
      </tr>
    <% end %>  
    </tbody>
  </table>
</div>

app/views/groups/new.html.erb
<h1 class="display-4 mt-5">Create new group</h1>
<%= render 'form' %>

app/views/groups/show.html.erb
<h1 class="display-4 mt-5"><%= @group.name%></h1>
<%= session[:current_group_id] %>
<div class="text-center mt-3">
  <%= link_to "Delete", group_path(@group), method: :delete, data: { confirm: "Are you sure?"} , class: "btn btn-outline-danger btn-lg justify-content-md-center"%>
  <%= link_to "Change group name", edit_group_path(@group), class: "btn btn-outline-warning btn-lg justify-content-md-center"  %>
  <%= link_to "Add members", new_member_path, class: "btn btn-outline-info btn-lg justify-content-md-center" %>
  <%= link_to "Create event", group_create_event_path(@group), class: "btn btn-outline-success btn-lg justify-content-md-center" %>
</div>
<div class="container mt-3" id="groups-index-container">
  <table class="table ">
    <thead>
      <tr>
        <th scope="col">Name</th> 
        <th scope="col">Email</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
    <% @members.each do |member| %>
      <tr>        
        <td><%= member.name %></td>
        <td><%= member.email %></td>        
        <td>
          <%= link_to "Delete", member_path(member), method: :delete, data: { confirm: "Are you sure?"} , class: "btn btn-outline-danger btn-sm"%>     
        </td>
      </tr>
    <% end %>  
    </tbody>
  </table>
</div>

app/views/layouts/_messages.html.erb
<div class="container">
    <% flash.each do |name, msg| %>
        <% if name == "notice" %>
          <div class="alert alert-success alert-dismissible fade show" role="alert">
            <%= msg %>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        <% elsif name == "alert" %>
          <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <%= msg %>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        <% end %>    
    <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container-fluid">
    <%= link_to "Secret Santa", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if logged_in? %>
          <%= link_to "Groups", groups_path, class: "nav-link" %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.username %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "Edit account", edit_user_path(current_user), class: "dropdown-item" %>
              <li><hr class="dropdown-divider"></li>
              <%= link_to "Log out", logout_path, class: "dropdown-item", method: :delete %>
            </ul>
          </li>
        <% else %>
          <%= link_to "Log in ", login_path, class: "nav-link" %>         
        <% end %>            
      </ul>
      <form class="d-flex">        
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Secretsanta</title>
    <%= favicon_link_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    
  <body>
    <%= render 'layouts/navigation' %>     
    <div id="page-content">
      <%= render 'layouts/messages' %>    
      <%= yield %>     
    </div>   
  </body>
</html>
 

app/views/members/_form.html.erb
<div class="input-group mb-3">       
   <%= form_with(model: @member, local: true) do |f|%>
    <%= f.text_field :name, class: "form-control shadow-lg rounded", placeholder: "Enter member's name" %>
    <%= f.text_field :email, class: "form-control shadow-lg rounded", placeholder: "Enter member's email" %>         
  <%end%> 
</div>

app/views/members/new.html.erb
<%= render 'shared/errors', obj: @member %>
<h1 class="display-4 mt-5">Add members to <%= Group.find_by_id(session[:current_group_id]).name %></h1>
<div class="container mt-3" id="members-input-container">
  <%= form_with(model: @member, local: true) do |f|%>
    <div class="input-group mb-3">       
      <%= f.text_field :name, class: "form-control shadow-lg rounded", placeholder: "Enter member's name" %>
      <%= f.text_field :email, class: "form-control shadow-lg rounded", placeholder: "Enter member's email" %>         
    </div>     
    <%= f.submit class:"btn btn-outline-secondary btn-lg right "%>
    <%end%> 
</div>    

app/views/members/show.html.erb
<h1 class="display-4">Members</h1>
<div class="container" id="members-input-container">
  <% form_with(@group.members, local: :true) do |f|%>
    <form class="row gy-2 gx-3 align-items-center">
      <div class="col-auto">        
        <div class="input-group">
          <%= f.label :name, class: "input-group-text" %>
        <div class="col-10"> 
          <%= f.text_field :name, class: "form-control shadow-lg rounded", placeholder: "Enter member name" %>
        </div>  
        </div>
      </div>  
      <div class="col-auto">        
        <div class="input-group">
          <%= f.label :email, class: "input-group-text" %>
        <div class="col-10"> 
          <%= f.text_field :email, class: "form-control shadow-lg rounded", placeholder: "Enter member email" %>
        </div>  
        </div>
      </div>  
      <div class="col-auto">
        <button type="submit" class="btn btn-danger">Delete</button>
      </div>
    </form>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="container mt-5">
  <div class="jumbotron text-center font-weight-bold" id="jumbotron-home">
    <strong><i><h1 class="display-4">Secret Santa</h1></i></strong>
    <p class="lead">Welcome on Secret Santa, free online gift exchange organizer.</p>    
    <p>To start just clik button below!</p>
    <p class="lead">
      <% if !logged_in? %>
        <%= link_to "Start", login_path, class: "btn btn-danger btn-lg"  %>    
      <%end%> 
    </p>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="container", id="errors-container">
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <h4 class="alert-heading">The following errors prevended <%= obj.class.name.downcase %> from being save</h4>
      <ul>
        <% obj.errors.full_messages.each do |msg|%>
          <FONT COLOR="#ff0000"><li><%= msg%></li></FONT>
        <% end %>
      </ul>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  </div>
<% end%>

app/views/users/_form.html.erb
<div class="container shadow-lg p-3 rounded mt-4" id="create-account-container">
  <%= form_with(model: @user, local: true) do |f|%>
    <div class="row">            
      <div class="card">
        <div class="card-body">
          <% if @user.new_record? %>
            <h5 class="card-title">Create new account</h5>                 
          <% else %>
            <h5 class="card-title">Edit your account</h5>        
          <% end %>
          <div class="col-12">
            <%= f.text_field :username, class: "form-control mt-3 rounded", placeholder: "Enter your username" %>
          </div> 
          <div class="col-12">
            <%= f.text_field :email, class: "form-control mt-3 rounded", placeholder: "Enter your email" %>
          </div>
          <div class="col-12">
            <%= f.password_field :password, class: "form-control mt-3 rounded", placeholder: "Enter your password" %>
          </div>
          <div class="card-body">
            <% if @user.new_record? %>
              <%= link_to "Back", login_path, data: { confirm: "Your account will be not created!"}, class: " btn btn-outline-secondary "%>
              <%= f.submit "Create new account" , class:"btn btn-outline-success right " %>
            <% else %>
              <%= link_to "Back", groups_path, data: { confirm: "Your account will be not updated!"}, class: " btn btn-outline-secondary "%>
              <%= f.submit "Update account" , class:"btn btn-outline-success right " %>
            <% end %> 
            <div>
            <% if @user == current_user %>              
              <%= link_to 'Delete account', user_path(@user), class: "btn btn-outline-danger right mt-3", method: :delete, data: { confirm: "Are you sure?" } %>              
            <%end%>
            </div>  
          </div>                             
        </div>        
      </div>              
    </div> 
  <% end %> 
</div>  

app/views/users/edit.html.erb
<strong><i><h1 class="display-4 font-italic mt-3 " style="text-align:center">Secret Santa</h1></i></strong>
<%= render 'form'%>

app/views/users/new.html.erb
<strong><i><h1 class="display-4 font-italic mt-3 " style="text-align:center">Secret Santa</h1></i></strong>
<%= render 'form'%>